#!/bin/sh
MODELS_DIR="../MoDeNaModels"

foamAging="${MODELS_DIR}/foamAging/src"
cmake -H${foamAging} -B${foamAging} && make --directory=${foamAging}

foamConductivity="${MODELS_DIR}/foamConductivity/src"
cmake -H${foamConductivity} -B${foamConductivity} && \
  make --directory=${foamConductivity}

solubility="${MODELS_DIR}/Solubility/src"
make --directory=${solubility}
