#!/usr/bin/python
'''

   ooo        ooooo           oooooooooo.             ooooo      ooo
   `88.       .888'           `888'   `Y8b            `888b.     `8'
    888b     d'888   .ooooo.   888      888  .ooooo.   8 `88b.    8   .oooo.
    8 Y88. .P  888  d88' `88b  888      888 d88' `88b  8   `88b.  8  `P  )88b
    8  `888'   888  888   888  888      888 888ooo888  8     `88b.8   .oP"888
    8    Y     888  888   888  888     d88' 888    .o  8       `888  d8(  888
   o8o        o888o `Y8bod8P' o888bood8P'   `Y8bod8P' o8o        `8  `Y888""8o

Copyright
    2014 MoDeNa Consortium, All rights reserved.

License
    This file is part of Modena.

    Modena is free software; you can redistribute it and/or modify it under
    the terms of the GNU General Public License as published by the Free
    Software Foundation, either version 3 of the License, or (at your option)
    any later version.

    Modena is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
    FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
    details.

    You should have received a copy of the GNU General Public License along
    with Modena.  If not, see <http://www.gnu.org/licenses/>.

Description
    Initialisation script for the Case 1.

Authors
    Henrik Rusche
    Pavel Ferkl

Contributors
'''

from modena import SurrogateModel
from modena.Strategy import Workflow2
# import solubility
import diffusivity
import gasConductivity
# import polymerConductivity # polymerConductivity is created by foamConductivity
import foamConductivity
from fireworks import LaunchPad
from fireworks.core.rocket_launcher import rapidfire
from fireworks.utilities.fw_serializers import load_object

# set up the LaunchPad and reset it
launchpad = LaunchPad()
launchpad.reset('', require_password=False)

initWfs = Workflow2([])
for m in SurrogateModel.get_instances():
    initWfs.addNoLink(m.initialisationStrategy().workflow(m))

# store workflow and launch it locally
launchpad.add_wf(initWfs)
rapidfire(launchpad)

# # Cheat to avoid refitting of cyclopentane solubility
# from pymongo import MongoClient
# url = 'mongodb://localhost:27017/'
# client = MongoClient(url)
# collection = client.test.surrogate_model
# collection.update(
#     {'_id': 'solubilityCyclopentane'},
#     {
#         '$set':
#         {
#             'inputs': {"T": {"argPos": 0, "max": 400, "min": 270}},
#         }
#     }
# )
