#!/bin/sh
MODELS_DIR="../MoDeNaModels"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo ${SCRIPT_DIR}

bubbleGrowth="${MODELS_DIR}/bubbleGrowth/src"
cmake -H${bubbleGrowth} -B${bubbleGrowth} && make --directory=${bubbleGrowth}

CFD_tool_3D="${MODELS_DIR}/CFD_tool_3D/src"
cd $CFD_tool_3D
./makeEigen
wmake
cd ../../../foamingProcess3D/
# cmake -H${CFD_tool_0D} -B${CFD_tool_0D} && \
# make --directory=${CFD_tool_0D}

solubility="${MODELS_DIR}/Solubility/src"

make --directory=${solubility}

surfaceTension="${MODELS_DIR}/SurfaceTension/src"
make --directory=${surfaceTension} DFT
