#!/bin/sh

set -x

# Go to eigen directory and make dynamic libraries, then move them to $FOAM_USER_LIBBIN
cd eigen	
mkdir obj
cd obj
mkdir dyn
mkdir sta 
cd ..
make dynamic 
mv libeigen.so $FOAM_USER_LIBBIN

# -----EOF
