#!/bin/sh

MODELS_DIR="../MoDeNaModels"

bubbleGrowth="${MODELS_DIR}/bubbleGrowth/src"
cmake -H${bubbleGrowth} -B${bubbleGrowth} && make --directory=${bubbleGrowth}

CFD_tool_0D="${MODELS_DIR}/CFD_tool_0D/src"
cmake -H${CFD_tool_0D} -B${CFD_tool_0D} && \
    make --directory=${CFD_tool_0D}
